# Generated by Django 3.1.5 on 2021-01-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answers_questiongroups_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='title',
            new_name='body',
        ),
    ]
