# Generated by Django 3.1.5 on 2021-01-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210111_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='body',
        ),
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
